/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtolyeRouteImport } from './routes/atolye'
import { Route as InsaRouteImport } from './routes/insa'
import { Route as ModerasyonRouteImport } from './routes/moderasyon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtolyeRoute = AtolyeRouteImport.update({
  id: '/atolye',
  path: '/atolye',
  getParentRoute: () => rootRouteImport,
} as any)
const InsaRoute = InsaRouteImport.update({
  id: '/insa',
  path: '/insa',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerasyonRoute = ModerasyonRouteImport.update({
  id: '/moderasyon',
  path: '/moderasyon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atolye': typeof AtolyeRoute
  '/insa': typeof InsaRoute
  '/moderasyon': typeof ModerasyonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atolye': typeof AtolyeRoute
  '/insa': typeof InsaRoute
  '/moderasyon': typeof ModerasyonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atolye': typeof AtolyeRoute
  '/insa': typeof InsaRoute
  '/moderasyon': typeof ModerasyonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atolye' | '/insa' | '/moderasyon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atolye' | '/insa' | '/moderasyon'
  id: '__root__' | '/' | '/atolye' | '/insa' | '/moderasyon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtolyeRoute: typeof AtolyeRoute
  InsaRoute: typeof InsaRoute
  ModerasyonRoute: typeof ModerasyonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atolye': {
      id: '/atolye'
      path: '/atolye'
      fullPath: '/atolye'
      preLoaderRoute: typeof AtolyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insa': {
      id: '/insa'
      path: '/insa'
      fullPath: '/insa'
      preLoaderRoute: typeof InsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderasyon': {
      id: '/moderasyon'
      path: '/moderasyon'
      fullPath: '/moderasyon'
      preLoaderRoute: typeof ModerasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtolyeRoute: AtolyeRoute,
  InsaRoute: InsaRoute,
  ModerasyonRoute: ModerasyonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
